# Generated by Django 4.2.1 on 2023-05-23 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Marke', models.CharField(max_length=80)),
                ('MOdelis', models.CharField(max_length=80)),
                ('Valstybinis', models.CharField(max_length=80)),
                ('VIN_kodas', models.CharField(max_length=80)),
                ('Klientas', models.CharField(max_length=80)),
            ],
        ),
    ]
